name: Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document​​
        uses: xu-cheng/latex-action@v4
        with:
          root_file: main.tex
          latexmk_use_xelatex: true
          latexmk_shell_escape: true
      - name: Commit and push PDF
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add main.pdf
          git commit -m "Update main.pdf" || echo "No changes to commit"
          git push
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          keep_files: true
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
